services:
  db:
    image: postgres:14.11
    env_file:
      - ./config/db/.env
    ports:
      - 5555:5432

  # redis:
  #   image: redis:alpine
  #   restart: always
  #   env_file:
  #     - ./config/redis/.env
  #   ports:
  #     - 6379:6379

  server:
    build:
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    env_file:
      - ./config/server/.env
    depends_on:
      - db
      # - redis
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "db:5432", "redis:6379"]
      interval: 10s
      timeout: 5m
      retries: 5
      start_period: 30s